### ISSUE TITLE
Trying to run the docker-compose.yml

### ISSUE THREAD

**Issue by MrGlenn-tech** [dorel14/3CX-Cdr-Tcp-Server#10]
Hi, 
Im trying to run this but when i try i get the error 

The Compose file './docker-compose.yml' is invalid because:
services.3cxcdrtcpserver.depends_on contains an invalid type, it should be an array

any suggestions ?

**Comment by dorel14** [comment]
Hello , i have updated docker compose and srv/Dockerfile 

Can you test it and close if ok ?
