### ISSUE TITLE
Sorry to bother you

### ISSUE THREAD

**Issue by MrGlenn-tech** [dorel14/3CX-Cdr-Tcp-Server#12]
Hi, 

Sorry to bother you trying to get it to work, but i cant for somereason been a while since i used docker. 

when i try to run it i get to errors. 

WARN[0000] /home/administrator/3CX-Cdr-Tcp-Server/docker-compose.yml: `version` is obsolete
env file /home/administrator/3CX-Cdr-Tcp-Server/.env not found: stat /home/administrator/3CX-Cdr-Tcp-Server/.env: no such file or directory

i did a git clone from your work. 

Do you have like an exampel on how a .env file should look like?

**Comment by dorel14** [comment]
Hello 
don't matter ,  this app needs to be tested by someone than me 

For the first part of you message ,  i have updated the docker-compose.yml

For the 2nd part ,  you have to create a .env file in your folder with the help of the template [[.env_model](https://github.com/dorel14/3CX-Cdr-Tcp-Server/blob/master/.env_model)](https://github.com/dorel14/3CX-Cdr-Tcp-Server/blob/master/.env_model)

**Comment by MrGlenn-tech** [comment]
I can beta test :) no worries but im guessing i will be bothering you. 

So i created the .env file copyd the info from the template you linked. 
not sure on what i should specify regarding the 
DB information ? dont the docker contain it´s own DB or did i missunderstand that so i need to install a db ? 
or is my google translate of since i copyd your text and translated it. 

And the Grafana info, is that just a security password that i need to add to my existing grafan when adding a new datasource ? 

This is what happens now when i try to use "docker compose up docker-compose-yml 

WARN[0000] /home/administrator/3CX-Cdr-Tcp-Server/docker-compose.yml: `version` is obsolete
no such service: docker-compose.yml (This error started when i created the .env file)

**Comment by dorel14** [comment]
You don't need to install a db ,  the docker compose will make it for you but need to put some information in the .env file in order to make the other containers to talk with db 

POSTGRES_USER=
POSTGRES_PASSWORD=
POSTGRES_SERVER=
POSTGRES_PORT=
POSTGRES_DB= 

For someone who has an already postgres server working  ,  it's possible to comment everything around postgres in docker-compose and only put the informations in the .env file

For grafana ,  the docker compose create a container with it  and the GF_SECURITY_ADMIN_PASSWORD in .env is to setup the admin password 

if you already have a grafana instance running ,  you don't need this container so you can comment or remove  this part of docker-compose and just set up a new source in your instance

**Comment by MrGlenn-tech** [comment]
So now grafana works and i can connect to the database 
but it seems to not collecting any data. 

i have set my 3cx instance to CDR / Active Socket and port to 5000
but no data is beeing collected. 
if i do a telnet ip and port from my 3cx server to my 3CX-Cdr-Tcp-Server it works for port 3000 and 5432 
but on 5000 i get connection refused seems to be that it is not listning on port 5000, 

Any clue about this issue?

**Comment by dorel14** [comment]
Hello 
For the moment FTP is not working ,  i have a bit of work to make it work well

For the others issues , i'll have a look next week i think ,

**Comment by MrGlenn-tech** [comment]
Hello, 

Ok thanks for the reply.

**Comment by dorel14** [comment]
Hello ,  i've made some changes ,  TCP server is now working in docker and the pull error message in not anymore shown ,  
Tel me if it's ok four you 

I have open an other issue for the ftp

**Comment by MrGlenn-tech** [comment]
Hi, 

Tested now no pull errors , put still getting connection refused to port 5000 on the server from my 3cx instanse. 
And looking at the DB that was created it still seems to have no tables. 

my .env looks like this in case it might help you? 


  GNU nano 7.2                                                                                     .env
#TZ informations
TZ=Europe/Stockholm

#Locales informations
LOCALE_LANGUAGE = sv-SE

# Db informations
POSTGRES_USER=test
POSTGRES_PASSWORD=test
POSTGRES_SERVER=localhost
POSTGRES_PORT=5432
POSTGRES_DB=main


#PG Admin informations
PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
PGADMIN_DEFAULT_PASSWORD=admin

#Grafane informations
GF_SECURITY_ADMIN_PASSWORD=test

#Prefered server type (FTP - TCP)
# If FTP , you need to set informations in #3cx FTP informations
# If TCP , you need to set informations in #3cx TCP Server port
SERVER_TYPE=TCP

#3cx FTP informations
FTP_3CX_HOST=
FTP_3CX_PORT=
FTP_3CX_LOGIN=
FTP_3CX_PASSWORD=
FTP_3CX_SRVDIR=
#Set interval in which ftp client will look at the server for new files
FTP_3CX_INTERVAL= 50

#3CX CDR file extension
3CX_FILEEXT=.csv

#3cx TCP Server port
SERVER_PORT=5000

#Api URL
API_URL=http://webapi:8000


#NFS Folder where cdr are uploaded from
#CDR_SERVER_IP=3cxcdrserver
#CDR_FOLDER="/volume1/test_docker"

#CDR folder on local server where to archives CDR files
LOCAL_CDR_FOLDER_ARCHIVE=/home/administrator/3CX-Cdr-Tcp-Server

**Comment by MrGlenn-tech** [comment]
But  i also see this with a docker ps -a

![image](https://github.com/dorel14/3CX-Cdr-Tcp-Server/assets/68515997/4c41c1de-d0cd-4bea-b9d6-1c5a86d51c8a)

Seems that nothing is running on port 5000 even tho the serverport is set to 5000

**Comment by dorel14** [comment]
Hello, vert strange, it is working here on m'y serveur


Can you test to set POSTGRES_SERVER=dB to use the postgres container and set postgres user and password to postgres 

TCP server container don't start because dB IS unhealthy

**Comment by MrGlenn-tech** [comment]
Hi, 

Did that and now it seems to work a alot better :) i can see that port 5000 is listning and that there is alot of tables in in the db, 
but still no data if i run

select count(*) from call_data_records
it just show 0 

I have set my 3cx instance to active socket and port 5000. 

Am i still missing something?

**Comment by dorel14** [comment]
Ok, good news if docker stack start working.

If field names hava change, not sure it will work , i need to have a look.

Can you close this issue and open another one as it is another problem ?
