### ISSUE TITLE
Ftp question

### ISSUE THREAD

**Issue by MrGlenn-tech** [dorel14/3CX-Cdr-Tcp-Server#18]
Hi, 

Im testing the ftp part with no luck so far. 
does the builtin ftp client handle sftp or just ftp at the moment?

**Comment by dorel14** [comment]
Hello 

Only FTP for the moment

**Comment by MrGlenn-tech** [comment]
Thanks for the reply, 

Then i know why it is not working since i dont have an ftp server installed on our 3cx applience server.

Are you considering to use sftp (over openssh) or something like scp in the futrue?

**Comment by dorel14** [comment]
I'll have a look at this

**Comment by dorel14** [comment]
Hello 
SFTP and SCP are now available, more testing is definitely needed, feel free to create issues.
I will certainly be slower to process them because I am going back to work

Enjoy
