### ISSUE TITLE
Compose file error 

### ISSUE THREAD

**Issue by MrGlenn-tech** [dorel14/3CX-Cdr-Tcp-Server#23]
Hi, 

getting issues when trying to use docker-compose , 
Seems to be a issue with the docker-compose.yml 

`ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'grafana'
Unsupported config option for volumes: 'pgdata'
`

Tested to fix the the docker-compose.yml but no matter what i do i get errors.

**Comment by dorel14** [comment]
Hello , i don't know what happen with your compose file ,  i have try to redownload the repo with a git pul and run a docker compose compose up without any problem ,  everything start

**Comment by MrGlenn-tech** [comment]
Hello, 

I have deleted the old docker images , removed the old folder. 
Then done a git clone, and when i run a docker-compose up i get the error that the docker-compose.yml error

**Comment by dorel14** [comment]
Can you put the content if the compose file in the issue ?

**Comment by MrGlenn-tech** [comment]
services:
  db:
    build:
      context: .
      dockerfile: ./db_folder/Dockerfile
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 60s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: ./webapi/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8004:8000
    command: bash -c  "/wait && uvicorn webapi.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    #"while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn webapi.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    environment:
      - WAIT_HOSTS=${POSTGRES_SERVER}:${POSTGRES_PORT}
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    healthcheck:
      test: curl ${API_URL}/healthcheck || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s


  # ui:
  #   build:
  #     context: .
  #     dockerfile: ./ui/Dockerfile
  #   restart: always
  #   depends_on:
  #     webapi:
  #       condition: service_healthy
  #   ports:
  #       - 8501:8501


  3cxcdrserver:
    build:
      context: .
      dockerfile: ./srv/Dockerfile
    tty: true
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      webapi:
        condition: service_healthy
    restart: always
    command: bash -c "/wait && python -m alembic upgrade head && python srv/runserver.py"
    environment:
      - WAIT_HOSTS=${POSTGRES_SERVER}:${POSTGRES_PORT}
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - cdr:/home/appuser/cdrfiles
      - ${LOCAL_CDR_FOLDER_ARCHIVE}:/home/appuser/cdrfiles/cdrfiles_archives

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5555:80
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data


  grafana:
    image: grafana/grafana-oss
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana_init/provisioning/:/etc/grafana/provisioning/
      - ./grafana_init/provisioning/dashboards/dashboard_files/:/var/lib/grafana/dashboards/

volumes:
   pgdata: {}
   pgadmin_data: {}
   grafana-storage: {}
   cdr: {}

**Comment by dorel14** [comment]
Thx

I have made 2 tests
1 - I delete my containers and images  , git clone in a new folder and docker compose up => everything is ok , it works in scp mode
2 - I delete containers and images , take your docker-compose.yml and docker compose up => same result , it works in scp mode

I don't know what can happen , perhaps have a look at your .env

**Comment by MrGlenn-tech** [comment]
Verry strange tired it fresh now and used SCP instead of testing with sftp, 
deleted all the old files did a new gitclone, 
copyd the template .env put the info in to it (the .env template contains some spaces just so you know) 

`Unsupported config option for volumes: 'cdr'
Unsupported config option for services: 'db'`

So something weird is going on mabey on my machine. but i tired restarting it as well. 
i will try to test on a fresh machine

**Comment by MrGlenn-tech** [comment]
`
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for volumes: 'pgdata'
Unsupported config option for services: 'webapi'
`
Tested on a fresh server, installed docker-compose and also tested with your dock-compose file still get unsupported config error.

**Comment by dorel14** [comment]
I don't understand what happen, which docker version and docker compose version do you use ?

What kind of server. Linux ? Windows ? Which os version ?

Is the user that you use authorised to create folders ? 

I have tested on my windows 11 computer and also on a debian without Anny problem

**Comment by MrGlenn-tech** [comment]
Im using `docker version 26.1.4` and `docker-compse version 1.19.0`

The machine is a virtual running `debian 12.5.0` 

i have tested with user root and administrator that has sudo privileges

**Comment by dorel14** [comment]
I have made some improvments in the docker compose file

**Comment by MrGlenn-tech** [comment]
Sorry to come with the bad news but i still get issues now on grafan-storage and webapi 

`ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for volumes: 'grafana-storage'
Unsupported config option for services: 'webapi'
`

**Comment by dorel14** [comment]
I read that your docker compose version IS not the latest, Can you try to update ?

**Comment by MrGlenn-tech** [comment]
Hi, 

updated docker-compose and i can now start it but i still encouter issues :( 

first of i get that webapi and pgadmin is unhealthy. 

and then 3cx-cdr-tcp-server_db ends up in a restarting loop with this in the logs. 

`The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".`

`Data page checksums are disabled.`

`initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
It contains a dot-prefixed/invisible file, perhaps due to it being a mount point.
Using a mount point directly as the data directory is not recommended.
Create a subdirectory under the mount point.
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.`


any suggestions ?

**Comment by dorel14** [comment]
I know where it comes from , new version will fix it

**Comment by dorel14** [comment]
Hello, fix is available, you can download latest version and close issue if ok
