### ISSUE TITLE
Problem with networking 

### ISSUE THREAD

**Issue by dorel14** [dorel14/3CX-Cdr-Tcp-Server#32]
So i did a new git clone, 

But now as soon as i do a docker-compose up the server stops responding to ping 
`Creating network "3cx-cdr-tcp-server_default` with the default driver then everything stops 
i can log in to the server terminal from the host where it seems "to work" but i cant confirme it.

_Originally posted by @MrGlenn-tech in https://github.com/dorel14/3CX-Cdr-Tcp-Server/issues/27#issuecomment-2145183615_

**Comment by MrGlenn-tech** [comment]
Solved that issue by adding this to the docker-compose file. 
since the standard network interfere with my current setup. 

    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana_init/provisioning/:/etc/grafana/provisioning/
      - ./grafana_init/provisioning/dashboards/dashboard_files/:/var/lib/grafana/dashboards/
    networks:
      - my_custom_network



networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

**Comment by dorel14** [comment]
Hello 
Nice to here , you found how to resolve it 

I have made an enhancement so that it's easier to specify the subnet in .env  with the items DOCKER_SUBNET and DOCKER_GATEWAY

Thx for the idea ,  i close the issue
